name: Make and deploy

on:
  push:
    branches:
      - master

jobs:
  make-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: sudo apt-get install texlive-latex-extra --no-install-recommends
      - name: Make
        run: ./make.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: true
          folder: dist
          git-config-name: GitHub Actions
          token: ${{ secrets.GITHUB_TOKEN }}
