name: Make and deploy

on:
  push:
    branches:
      - master

jobs:
  make-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: sudo apt-get install texlive-latex-extra --no-install-recommends
      - name: Make
        run: ./make.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
